### ISSUE TITLE
Current issues

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/tajawal#1]
Just did a QA on the ttfs.

Our api doesn't support UltraLight weights. Can we renamed the styles to the following:

- Extrabold --> ExtraBold
- Ultralight --> ExtraLight

https://docs.google.com/spreadsheets/d/1ckHigO7kRxbm9ZGVQwJ6QJG_HjV_l_IRWJ_xeWnTSBg/edit#gid=0

----

The ttfs don't pass ots, https://github.com/khaledhosny/ots

>> com.google.fonts/check/036 with ((u'font[0]', '/Users/marc/Documents/googlefonts/manual_font_cleaning/Tajawal/fonts/ttf/Tajawal-Regular.ttf'),)
   Checking with ots-sanitize.
 * FAIL: ots-sanitize returned an error code. Output follows :

ERROR: Layout: glyph range is overlapping.in range 11
ERROR: GDEF: Invalid glyph classes
ERROR: GDEF: Failed to parse table
Failed to sanitize file!

----

The fsType on all fonts must be set to 0, https://github.com/googlefonts/gf-docs/blob/master/ProjectChecklist.md#fstype

----

fsSelection and macStyle bits are off.

Bold

>> com.google.fonts/check/129 with ((u'font[0]', '/Users/marc/Documents/googlefonts/manual_font_cleaning/Tajawal/fonts/ttf/Tajawal-Bold.ttf'),)
   Checking OS/2 fsSelection value.
 * FAIL: OS/2 fsSelection REGULAR bit should be reset.
 * FAIL: OS/2 fsSelection BOLD bit should be set.

   Result: FAIL

>> com.google.fonts/check/131 with ((u'font[0]', '/Users/marc/Documents/googlefonts/manual_font_cleaning/Tajawal/fonts/ttf/Tajawal-Bold.ttf'),)
   Checking head.macStyle value.
 * FAIL: head macStyle BOLD bit should be set.

   Result: FAIL

Make sure the macStyle, fsSelection values follow the fonts here https://github.com/googlefonts/OswaldFont/tree/master/fonts/ttf

These findings come from our QA tool, fontbakery, https://github.com/googlefonts/fontbakery

**Comment by JuergenWillrodt** [comment]
This has been fixed.
