### ISSUE TITLE
Build script or instructions

### ISSUE THREAD

**Issue by davelab6** [googlefonts/tajawal#3]
If I take the files in https://github.com/URWPP/Tajawal/tree/master/source/2-production/Tajawal-Black then how do I build them with the FDK?

**Comment by JuergenWillrodt** [comment]
There is a Readme.md file in https://github.com/URWPP/Tajawal/tree/master/source
There you will find a description how to create TTF and OTF. You need the URW programs IKED and OTM to do that.

**Comment by davelab6** [comment]
The readme says "to change certain metric values" - this step is very
vague. I can't reproduce the binaries from the sources following these
instructions. Please update them to enable reproduction of the binaries.

Also since that repo is private I suggest deleting it, since this repo is
now the "upstream" home for the project.

**Comment by JuergenWillrodt** [comment]
The Readme has been modified and is now more detailed.
 The private repo will be deleted.

**Comment by davelab6** [comment]
Thank you! 

@m4rc1e do you think https://github.com/googlefonts/tajawal/tree/master/source is sufficient?

**Comment by m4rc1e** [comment]
Its pretty clear. However, the instructions use a proprietary URW++/DTL tool called IKED, which i don't think is OSS

**Comment by davelab6** [comment]
Sure, but most fonts use glyphsapp to build which is also proprietary
