### ISSUE TITLE
Unzip UFOs

### ISSUE THREAD

**Issue by davelab6** [googlefonts/tajawal#4]
The UFOs in the drawing source directory are needlessly zipped. 

Remove the zips and add the unzipped files :)

**Comment by JuergenWillrodt** [comment]
UFO stores every character as a single file, this adds up to about 6000 files. We can only download 100 at a time so the zip-file seems to be appropriate.

**Comment by davelab6** [comment]
What do you mean you can only download 100 files at a time? I completely
don't understand that.

GitHub.com/DaltonMaag/scope-one is another good reference repo that uses
UFO.

**Comment by JuergenWillrodt** [comment]
I have used the download file options and the message I get from github is:
Oops, that are many files. Please try with less than 100 files. 

I don´t understand that either.

**Comment by davelab6** [comment]
That's fine; use git :)
